In [2]:
import numpy as np
import pandas as pd
import ast

In [6]:
track = pd.read_csv(r'C:\Users\Xsistech\Documents\music recommendation system\track_data_final.csv')
spotify = pd.read_csv(r'C:\Users\Xsistech\Documents\music recommendation system\spotify_data clean.csv')

In [7]:
track.head()

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,09/11/2009,58,compilation
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,13/01/2023,1,single
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),09/04/2021,26,album
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,30/07/2021,16,album
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,01/01/2010,13,album

In [8]:
spotify.head()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39

In [9]:
music = pd.concat([spotify, track]) # merging the two datasets together
music.head()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min,track_duration_ms
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77.0,2812821.0,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55,NaN
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64.0,2363438.0,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07,NaN
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48.0,193302.0,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55,NaN
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77.0,2813710.0,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69,NaN
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48.0,8682.0,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39,NaN

In [12]:
music = music[['track_id','album_id','track_name','artist_name','artist_genres','album_name']]
music = music[music['artist_genres'].notna() & (music['artist_genres'] != '[]')]
music['tags'] = music['artist_genres'] + ' ' + music['album_name'] + ' ' + music['artist_name']
music.head()

,track_id,album_id,track_name,artist_name,artist_genres,album_name,tags
0,3EJS5LyekDim1Tf5rBFmZl,5QRFnGnBeMGePBKF2xTz5z,Trippy Mane (ft. Project Pat),Diplo,moombahton,"d00mscrvll, Vol. 1","moombahton d00mscrvll, Vol. 1 Diplo"
1,1oQW6G2ZiwMuHqlPpP27DB,4SUmmwnv0xTjRcLdjczGg2,OMG!,Yelawolf,"country hip hop, southern hip hop",OMG!,"country hip hop, southern hip hop OMG! Yelawolf"
3,67rW0Zl7oB3qEpD5YWWE5w,5QRFnGnBeMGePBKF2xTz5z,Still Get Like That (ft. Project Pat & Starrah),Diplo,moombahton,"d00mscrvll, Vol. 1","moombahton d00mscrvll, Vol. 1 Diplo"
4,15xptTfRBrjsppW0INUZjf,06FDIpSHYmZAZoyuYtc7kd,ride me like a harley,Rumelis,dark r&b,come closer / ride me like a harley,dark r&b come closer / ride me like a harley R...
5,4ccpCcZYseq8VrPMK1EDs0,2NQv9p3ZQW0Ed1LB9enix8,BLEED,Minzie,dark r&b,BLEED,dark r&b BLEED Minzie

In [13]:
# Removes [, ], and ' from the strings
music['tags'] = music['tags'].str.replace(r"[\[\]',]", "", regex=True)

music['tags'] = music['tags'].apply(lambda x: x.lower())
music['tags']

0                      moombahton d00mscrvll vol. 1 diplo
1          country hip hop southern hip hop omg! yelawolf
3                      moombahton d00mscrvll vol. 1 diplo
4       dark r&b come closer / ride me like a harley r...
5                                   dark r&b bleed minzie
                              ...
8767                         pop teenage dream katy perry
8768    metal heavy metal rock stoner rock doom metal ...
8770    bedroom pop if i could make it go quiet girl i...
8776                              indie rock twilight bôa
8777          rap hip hop the marshall mathers lp2 eminem
Name: tags, Length: 9513, dtype: str

In [14]:
music = music.drop_duplicates('track_name')
music = music.reset_index(drop=True)
music

,track_id,album_id,track_name,artist_name,artist_genres,album_name,tags
0,3EJS5LyekDim1Tf5rBFmZl,5QRFnGnBeMGePBKF2xTz5z,Trippy Mane (ft. Project Pat),Diplo,moombahton,"d00mscrvll, Vol. 1",moombahton d00mscrvll vol. 1 diplo
1,1oQW6G2ZiwMuHqlPpP27DB,4SUmmwnv0xTjRcLdjczGg2,OMG!,Yelawolf,"country hip hop, southern hip hop",OMG!,country hip hop southern hip hop omg! yelawolf
2,67rW0Zl7oB3qEpD5YWWE5w,5QRFnGnBeMGePBKF2xTz5z,Still Get Like That (ft. Project Pat & Starrah),Diplo,moombahton,"d00mscrvll, Vol. 1",moombahton d00mscrvll vol. 1 diplo
3,15xptTfRBrjsppW0INUZjf,06FDIpSHYmZAZoyuYtc7kd,ride me like a harley,Rumelis,dark r&b,come closer / ride me like a harley,dark r&b come closer / ride me like a harley r...
4,4ccpCcZYseq8VrPMK1EDs0,2NQv9p3ZQW0Ed1LB9enix8,BLEED,Minzie,dark r&b,BLEED,dark r&b bleed minzie
...,...,...,...,...,...,...,...
4706,4VrWlk8IQxevMvERoX08iC,3xFSl9lIRaYXIYkIn3OIl9,Chandelier,Sia,"['dark r&b','pop']",1000 Forms Of Fear,dark r&bpop 1000 forms of fear sia
4707,1ZuNmHmJn8QiS9kRYZuLNJ,2G4BowCb2oGMU2bfCdiWLq,Wait a Minute!,WILLOW,"['indie rock','pop']",Coldest Winter,indie rockpop coldest winter willow
4708,1FnJrD4ddWFNfCfKTiWY0w,2y8d4zbifvkrpASJeTMDnE,"Young Love - from ""Little Women"" Soundtrack",Alexandre Desplat,['soundtrack'],Little Women (Original Motion Picture Soundtrack),soundtrack little women (original motion pictu...
4709,4wH4dJgrsxONID6KS2tDQM,2yboV2QBcVGEhcRlYuPpDT,Maneater,Nelly Furtado,['pop'],Loose,pop loose nelly furtado
4710,42qNWdLKCI41S4uzfamhFM,7sGYAV0xv7ZfAMzIpMl8m1,Duvet,bôa,['indie rock'],Twilight,indie rock twilight bôa

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
# TfidfVectorizer turns your tags column into a giant grid of numbers. Computers only understand numbers
tfidf = TfidfVectorizer(stop_words='english')
# Ignore the most common English words (the, as, in, a...). Don't count them when you're trying to figure out what this song is about.
tfidf_matrix = tfidf.fit_transform(music['tags']) # transform words into numbers (computer language)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
# compare every single song against every other song in your dataset

In [20]:
def get_recommendations(track_name, cosine_sim=cosine_sim):
  idx = music[music['track_name'] == track_name].index[0]
  sim_scores = list(enumerate(cosine_sim[idx])) # to iterate through a sequence and also keep track of the index of each item
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:11] # Get top 10 similar music
  music_indices = [i[0] for i in sim_scores] # extract the music_indices
  return music[['track_name', 'artist_name']].iloc[music_indices]

In [24]:
get_recommendations('deja vu')

                        track_name     artist_name
1343               drivers license  Olivia Rodrigo
1344                enough for you  Olivia Rodrigo
1345                favorite crime  Olivia Rodrigo
1346                      good 4 u  Olivia Rodrigo
1347                       happier  Olivia Rodrigo
1348                    hope ur ok  Olivia Rodrigo
1349            jealousy, jealousy  Olivia Rodrigo
1352                       traitor  Olivia Rodrigo
1353  1 step forward, 3 steps back  Olivia Rodrigo
1354                        brutal  Olivia Rodrigo

In [25]:
import pickle
with open('music_recommendation_model.pkl', 'wb') as f:
    pickle.dump((music, cosine_sim),f)